### ISSUE TITLE
PMD rule violation found

### ISSUE THREAD

**Issue by Gauravsinghania54** [kochetkov-ma/allure-server#43]
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':pmdMain'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:208)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:206)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:187)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)

**Comment by Gauravsinghania54** [comment]
<img width="1469" alt="Screen Shot 2021-12-20 at 1 07 24 PM" src="https://user-images.githubusercontent.com/30242965/146819576-97f1a068-4046-4fbe-9f64-f680c49d3c14.png">

**Comment by Gauravsinghania54** [comment]
When I try to build the project , I got this PMD issue , I pulled the latest code but still how can we fix this ? Any idea would be appreciated.

**Comment by Gauravsinghania54** [comment]
Nevermind I was able to solve this
