### ISSUE TITLE
Generate report fail, http://192.168.137.48:8080/api/report

### ISSUE THREAD

**Issue by LQJ999** [kochetkov-ma/allure-server#92]
Generate report，
![image](https://github.com/user-attachments/assets/fcbc10bc-ce58-432b-a57f-fe0f02f481e4)
Generate fail，Ask for help
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed: java.lang.InternalError: Summary file not found... ] with root cause

java.lang.InternalError: Summary file not found...
        at ru.iopump.qa.allure.helper.plugin.CustomReportMetaPlugin.lambda$onGenerationFinish$3(CustomReportMetaPlugin.java:66) ~[!/:2.13.4]
        at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[na:na]
        at ru.iopump.qa.allure.helper.plugin.CustomReportMetaPlugin.onGenerationFinish(CustomReportMetaPlugin.java:66) ~[!/:2.13.4]
        at ru.iopump.qa.allure.helper.AllureReportGenerator.lambda$generate$7(AllureReportGenerator.java:112) ~[!/:2.13.4]
        at ru.iopump.qa.allure.helper.AllureReportGenerator.evaluateListener(AllureReportGenerator.java:140) ~[!/:2.13.4]
        at ru.iopump.qa.allure.helper.AllureReportGenerator.lambda$generate$8(AllureReportGenerator.java:112) ~[!/:2.13.4]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:na]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1709) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[na:na]
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:759) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1458) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2034) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:189) ~[na:na]

**Comment by LQJ999** [comment]
Path problem on windows

**Comment by triste-liu** [comment]
how to fix it?
